/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    AStyleProvider: typeof import('ant-design-vue/es')['StyleProvider']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BasicButtons: typeof import('./src/components/commons/basicButtons.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Hierarchical: typeof import('./src/components/commons/hierarchical.vue')['default']
    Interaction: typeof import('./src/components/commons/interaction.vue')['default']
    KAdvancedKeySettings: typeof import('./src/components/keyboardModule/functionSettings/kAdvancedKeySettings.vue')['default']
    KChangeKeySettings: typeof import('./src/components/keyboardModule/functionSettings/kChangeKeySettings.vue')['default']
    KeyboardModule: typeof import('./src/components/keyboardModule/index.vue')['default']
    KLightingSettings: typeof import('./src/components/keyboardModule/functionSettings/kLightingSettings.vue')['default']
    KMagneticAxisCalibration: typeof import('./src/components/keyboardModule/functionSettings/kMagneticAxisCalibration.vue')['default']
    KOtherSettings: typeof import('./src/components/keyboardModule/functionSettings/kOtherSettings.vue')['default']
    KPerformanceSettings: typeof import('./src/components/keyboardModule/functionSettings/kPerformanceSettings.vue')['default']
    KTriggerSettings: typeof import('./src/components/keyboardModule/functionSettings/kTriggerSettings.vue')['default']
    LoadComp: typeof import('./src/components/commons/loadComp.vue')['default']
    MacroSettings: typeof import('./src/components/commons/macroSettings.vue')['default']
    MChangeKeySettings: typeof import('./src/components/mouseMoudule/functionSettings/mChangeKeySettings.vue')['default']
    MDPISettings: typeof import('./src/components/mouseMoudule/functionSettings/mDPISettings.vue')['default']
    MLightingSettings: typeof import('./src/components/mouseMoudule/functionSettings/mLightingSettings.vue')['default']
    MOtherSettings: typeof import('./src/components/mouseMoudule/functionSettings/mOtherSettings.vue')['default']
    MouseMoudule: typeof import('./src/components/mouseMoudule/index.vue')['default']
    MPerformanceSettings: typeof import('./src/components/mouseMoudule/functionSettings/mPerformanceSettings.vue')['default']
    NoDevicesConnected: typeof import('./src/components/commons/noDevicesConnected.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/commons/slider.vue')['default']
    TitleBarStyle: typeof import('./src/components/commons/titleBarStyle.vue')['default']
    VueColorPicker: typeof import('./src/components/commons/vueColorPicker.vue')['default']
  }
}
