// 键盘基本按键区域
import reduce from '../assets/keyIcon/reduce-icon.webp' // 缩小
import zoomIn from '../assets/keyIcon/zoomIn-icon.webp' // 放大
import reset from '../assets/keyIcon/reset-icon.webp' // 复位
import recovery from '../assets/keyIcon/recovery-icon.webp' // 恢复
import undo from '../assets/keyIcon/undo-icon.webp' // 撤销
import selectAll from '../assets/keyIcon/selectAll-icon.webp' // 全选
import create from '../assets/keyIcon/create-icon.webp' // 新建
import copy from '../assets/keyIcon/copy-icon.webp' // 复制
import cut from '../assets/keyIcon/cut-icon.webp' // 剪切
import paste from '../assets/keyIcon/paste-icon.webp' // 粘贴
import save from '../assets/keyIcon/save-icon.webp' // 保存
import open from '../assets/keyIcon/open-icon.webp' // 打开
import newItem from '../assets/keyIcon/newItem-icon.webp' // 新建项
import closeItem from '../assets/keyIcon/closeItem-icon.webp' // 关闭项
import back from '../assets/keyIcon/back-icon.webp' // 后退(键盘)
import forward from '../assets/keyIcon/forward-icon.webp' // 前进(键盘)
import taskBar from '../assets/keyIcon/taskBar-icon.webp' // 任务栏
import openDescription from '../assets/keyIcon/openDescription-icon.webp' // 打开叙述
import loopTaskBarApp from '../assets/keyIcon/loopTaskBarApp-icon.webp' // 循环任务栏应用程序
import actionCenter from '../assets/keyIcon/actionCenter-icon.webp' // 行动中心
import fileExplorer from '../assets/keyIcon/fileExplorer-icon.webp' // 文件资源管理器
import windowsSettingsCenter from '../assets/keyIcon/windowsSettingsCenter-icon.webp' // Windows设置中心
import castToOtherDevice from '../assets/keyIcon/castToOtherDevice-icon.webp' // 投屏到其他设备
import jumpToTray from '../assets/keyIcon/jumpToTray-icon.webp' // 跳转到托盘
import startXboxGameBar from '../assets/keyIcon/startXboxGameBar-icon.webp' // 启动xbox游戏栏
import run from '../assets/keyIcon/run-icon.webp' // 运行
import search from '../assets/keyIcon/search-icon.webp' // 搜索
import displaySettings from '../assets/keyIcon/displaySettings-icon.webp' // 显示设置
import simpleMenu from '../assets/keyIcon/simpleMenu-icon.webp' // 简易菜单
import emojiBox from '../assets/keyIcon/emojiBox-icon.webp' // 表情框
import startMenu from '../assets/keyIcon/startMenu-icon.webp' // 开始菜单
import switchWindow from '../assets/keyIcon/switchWindow-icon.webp' // 转换窗口
import endApp from '../assets/keyIcon/endApp-icon.webp' // 结束应用
import switchToNextApp from '../assets/keyIcon/switchToNextApp-icon.webp' // 切换到下一个应用
import mouseRight from '../assets/keyIcon/mouseLeft-icon.webp' // 鼠标左键
import mouseLeft from '../assets/keyIcon/mouseRight-icon.webp' // 鼠标右键
import mouseMiddle from '../assets/keyIcon/mouseMiddle-icon.webp' // 鼠标中键
import mouseForward from '../assets/keyIcon/mouseForward-icon.webp' // 鼠标前进
import mouseBackward from '../assets/keyIcon/mouseBackward-icon.webp' // 鼠标后退
import mouseWheelUp from '../assets/keyIcon/mouseWheelUp-icon.webp' // 鼠标滚轮上
import mouseWheelDown from '../assets/keyIcon/mouseWheelDown-icon.webp' // 鼠标滚轮下
import playPause from '../assets/keyIcon/playPause-icon.webp' // 播放/暂停
import mute from '../assets/keyIcon/mute-icon.webp' // 静音
import stopPlay from '../assets/keyIcon/stopPlay-icon.webp' // 停止播放
import previousTrack from '../assets/keyIcon/previousTrack-icon.webp' // 上一曲
import nextTrack from '../assets/keyIcon/nextTrack-icon.webp' // 下一曲
import volumeUp from '../assets/keyIcon/volumeUp-icon.webp' // 音量+
import volumeDown from '../assets/keyIcon/volumeDown-icon.webp' // 音量-
import browserHomeIcon from '../assets/keyIcon/browserHomeIcon-icon.webp' // 浏览器首页
import calculator from '../assets/keyIcon/calculator-icon.webp' // 计算器
import email from '../assets/keyIcon/email-icon.webp' // 邮箱
import computer from '../assets/keyIcon/computer-icon.webp' // 计算机
import bookmark from '../assets/keyIcon/bookmark-icon.webp' // 收藏夹
import closeWindow from '../assets/keyIcon/closeWindow-icon.webp' // 关闭窗口
import lockComputer from '../assets/keyIcon/lockComputer-icon.webp' // 计算机锁定
import showDesktop from '../assets/keyIcon/showDesktop-icon.webp' // 显示桌面
import windowsSecurityScreen from '../assets/keyIcon/windowsSecurityScreen-icon.webp' // Windows安全屏幕
import taskManager from '../assets/keyIcon/taskManager-icon.webp' // 任务管理器
import screenBrightnessUp from '../assets/keyIcon/screenBrightnessUp-icon.webp' // 屏幕亮度+
import screenBrightnessDown from '../assets/keyIcon/screenBrightnessDown-icon.webp' // 屏幕亮度-



export function keyboardKeyArray() {
    return [
        {
            title: "基础字符",
            keys: [
                {
                    keyName: 'Esc',
                    name: 'Esc',
                    keyID: 10027,
                    KeyCode: '20 00 29',
                    top: 0,
                    left: 0,
                    width: 43,
                    height: 43,
                    tips: '常用于退出、取消、删除等功能',
                },
                {
                    keyName: 'F1',
                    name: 'F1',
                    keyID: 10042,
                    KeyCode: '20 00 3A',
                    top: 0,
                    left: 88,
                    width: 43,
                    height: 43,
                    tips: 'F1',
                },
                {
                    keyName: 'F2',
                    name: 'F2',
                    keyID: 10043,
                    KeyCode: '20 00 3B',
                    top: 0,
                    left: 132,
                    width: 43,
                    height: 43,
                    tips: 'F2',
                },
                {
                    keyName: 'F3',
                    name: 'F3',
                    keyID: 10044,
                    KeyCode: '20 00 3C',
                    top: 0,
                    left: 176,
                    width: 43,
                    height: 43,
                    tips: 'F3',
                },
                {
                    keyName: 'F4',
                    name: 'F4',
                    keyID: 10045,
                    KeyCode: '20 00 3D',
                    top: 0,
                    left: 220,
                    width: 43,
                    height: 43,
                    tips: 'F4',
                },
                {
                    keyName: 'F5',
                    name: 'F5',
                    keyID: 10046,
                    KeyCode: '20 00 3E',
                    top: 0,
                    left: 284,
                    width: 43,
                    height: 43,
                    tips: 'F5',
                },
                {
                    keyName: 'F6',
                    name: 'F6',
                    keyID: 10047,
                    KeyCode: '20 00 3F',
                    top: 0,
                    left: 328,
                    width: 43,
                    height: 43,
                    tips: 'F6',
                },
                {
                    keyName: 'F7',
                    name: 'F7',
                    keyID: 10048,
                    KeyCode: '20 00 40',
                    top: 0,
                    left: 372,
                    width: 43,
                    height: 43,
                    tips: 'F7',
                },
                {
                    keyName: 'F8',
                    name: 'F8',
                    keyID: 10049,
                    KeyCode: '20 00 41',
                    top: 0,
                    left: 416,
                    width: 43,
                    height: 43,
                    tips: 'F8',
                },
                {
                    keyName: 'F9',
                    name: 'F9',
                    keyID: 10050,
                    KeyCode: '20 00 42',
                    top: 0,
                    left: 480,
                    width: 43,
                    height: 43,
                    tips: 'F9',
                },
                {
                    keyName: 'F10',
                    name: 'F10',
                    keyID: 10051,
                    KeyCode: '20 00 43',
                    top: 0,
                    left: 524,
                    width: 43,
                    height: 43,
                    tips: 'F10',
                },
                {
                    keyName: 'F11',
                    name: 'F11',
                    keyID: 10052,
                    KeyCode: '20 00 44',
                    top: 0,
                    left: 568,
                    width: 43,
                    height: 43,
                    tips: 'F11',
                },
                {
                    keyName: 'F12',
                    name: 'F12',
                    keyID: 10053,
                    KeyCode: '20 00 45',
                    top: 0,
                    left: 612,
                    width: 43,
                    height: 43,
                    tips: 'F12',
                },
                {
                    keyName: 'PRTSC',
                    name: 'PRTSC',
                    keyID: 10085,
                    KeyCode: '20 00 46',
                    top: 0,
                    left: 676,
                    width: 43,
                    height: 43,
                    tips: '截屏键(全称:Print Screen)',
                },
                {
                    keyName: 'SOCK',
                    name: 'SOCK',
                    keyID: 10087,
                    KeyCode: '20 00 47',
                    top: 0,
                    left: 720,
                    width: 43,
                    height: 43,
                    tips: '滚动锁定键(全称:ScrollLock)',
                },
                {
                    keyName: 'PAUSE',
                    name: 'PAUSE',
                    keyID: 10086,
                    KeyCode: '20 00 48',
                    top: 0,
                    left: 764,
                    width: 43,
                    height: 43,
                    tips: '中断暂停键(全称:Pause Break)/',
                },
                {
                    keyName: '`~',
                    name: '`~',
                    keyID: 10064,
                    KeyCode: '20 00 35',
                    top: 44,
                    left: 0,
                    width: 43,
                    height: 43,
                    tips: '单击为`按住SHIFT单击为~',
                },
                {
                    keyName: '1!',
                    name: '1!',
                    keyID: 10075,
                    KeyCode: '20 00 1E',
                    top: 44,
                    left: 44,
                    width: 43,
                    height: 43,
                    tips: '单击为1按住SHIFT单击为!',
                },
                {
                    keyName: '2@',
                    name: '2@',
                    keyID: 10076,
                    KeyCode: '20 00 1F',
                    top: 44,
                    left: 88,
                    width: 43,
                    height: 43,
                    tips: '单击为2按住SHIFT单击为@',
                },
                {
                    keyName: '3#',
                    name: '3#',
                    keyID: 10077,
                    KeyCode: '20 00 20',
                    top: 44,
                    left: 132,
                    width: 43,
                    height: 43,
                    tips: '单击为3按住SHIFT单击为#',
                },
                {
                    keyName: '4$',
                    name: '4$',
                    keyID: 10078,
                    KeyCode: '20 00 21',
                    top: 44,
                    left: 176,
                    width: 43,
                    height: 43,
                    tips: '单击为4按住SHIFT单击为$',
                },
                {
                    keyName: '5%',
                    name: '5%',
                    keyID: 10079,
                    KeyCode: '20 00 22',
                    top: 44,
                    left: 220,
                    width: 43,
                    height: 43,
                    tips: '单击为5按住SHIFT单击为%',
                },
                {
                    keyName: '6^',
                    name: '6^',
                    keyID: 10080,
                    KeyCode: '20 00 23',
                    top: 44,
                    left: 264,
                    width: 43,
                    height: 43,
                    tips: '单击为6按住SHIFT单击为^',
                },
                {
                    keyName: '7&',
                    name: '7&',
                    keyID: 10081,
                    KeyCode: '20 00 24',
                    top: 44,
                    left: 308,
                    width: 43,
                    height: 43,
                    tips: '单击为7按住SHIFT单击为&',
                },
                {
                    keyName: '8*',
                    name: '8*',
                    keyID: 10082,
                    KeyCode: '20 00 25',
                    top: 44,
                    left: 352,
                    width: 43,
                    height: 43,
                    tips: '单击为8按住SHIFT单击为*',
                },
                {
                    keyName: '9(',
                    name: '9(',
                    keyID: 10083,
                    KeyCode: '20 00 26',
                    top: 44,
                    left: 396,
                    width: 43,
                    height: 43,
                    tips: '单击为9按住SHIFT单击为(',
                },
                {
                    keyName: '0)',
                    name: '0)',
                    keyID: 10084,
                    KeyCode: '20 00 27',
                    top: 44,
                    left: 440,
                    width: 43,
                    height: 43,
                    tips: '单击为0按住SHIFT单击为)',
                },

                {
                    keyName: '-_',
                    name: '-_',
                    keyID: 10065,
                    KeyCode: '20 00 2D',
                    top: 44,
                    left: 484,
                    width: 43,
                    height: 43,
                    tips: '单击为-按住SHIFT单击为_',
                },
                {
                    keyName: '=+',
                    name: '=+',
                    keyID: 10066,
                    KeyCode: '20 00 2E',
                    top: 44,
                    left: 528,
                    width: 43,
                    height: 43,
                    tips: '单击为=按住SHIFT单击为+',
                },
                {
                    keyName: 'Back——space',
                    name: 'Back——space',
                    keyID: 10030,
                    KeyCode: '20 00 2A',
                    top: 44,
                    left: 572,
                    width: 80,
                    height: 43,
                    tips: '删除光标前面的字符或元素',
                },
                {
                    keyName: 'INS',
                    name: 'INS',
                    keyID: 10054,
                    KeyCode: '20 00 49',
                    top: 44,
                    left: 676,
                    width: 43,
                    height: 43,
                    tips: '插入键(全称:Insert)',
                },
                {
                    keyName: 'HOME',
                    name: 'HOME',
                    keyID: 10055,
                    KeyCode: '20 00 4A',
                    top: 44,
                    left: 720,
                    width: 43,
                    height: 43,
                    tips: '回到窗口的初始位置或回到本行的最前端',
                },
                {
                    keyName: 'PGUP',
                    name: 'PGUP',
                    keyID: 10056,
                    KeyCode: '20 00 4B',
                    top: 44,
                    left: 764,
                    width: 43,
                    height: 43,
                    tips: '将页面向上滑动(全称:PageUp)',
                },
                {
                    keyName: 'NUM',
                    name: 'NUM',
                    keyID: 10088,
                    KeyCode: '20 00 53',
                    top: 44,
                    left: 828,
                    width: 43,
                    height: 43,
                    tips: '切换数字键盘的工作模式(全称:Number Lock)',
                },
                {
                    keyName: '/',
                    name: '/',
                    keyID: 10089,
                    KeyCode: '20 00 54',
                    top: 44,
                    left: 872,
                    width: 43,
                    height: 43,
                    tips: '/',
                },
                {
                    keyName: '*',
                    name: '*',
                    keyID: 10090,
                    KeyCode: '20 00 55',
                    top: 44,
                    left: 916,
                    width: 43,
                    height: 43,
                    tips: '*',
                },
                {
                    keyName: '-',
                    name: '-',
                    keyID: 10091,
                    KeyCode: '20 00 56',
                    top: 44,
                    left: 960,
                    width: 43,
                    height: 43,
                    tips: '-',
                },
                {
                    keyName: 'Tab',
                    name: 'Tab',
                    keyID: 10028,
                    KeyCode: '20 00 2B',
                    top: 88,
                    left: 0,
                    width: 60,
                    height: 43,
                    tips: '让光标在不同的字段或单元格之间快速切换(全称:Tabulator)',
                },
                {
                    keyName: 'Q',
                    name: 'Q',
                    keyID: 10017,
                    KeyCode: '20 00 14',
                    top: 88,
                    left: 64,
                    width: 43,
                    height: 43,
                    tips: 'Q和q键',
                },
                {
                    keyName: 'W',
                    name: 'W',
                    keyID: 10023,
                    KeyCode: '20 00 1A',
                    top: 88,
                    left: 108,
                    width: 43,
                    height: 43,
                    tips: 'W和w键',
                },
                {
                    keyName: 'E',
                    name: 'E',
                    keyID: 10005,
                    KeyCode: '20 00 08',
                    top: 88,
                    left: 152,
                    width: 43,
                    height: 43,
                    tips: 'E和e键',
                },
                {
                    keyName: 'R',
                    name: 'R',
                    keyID: 10018,
                    KeyCode: '20 00 15',
                    top: 88,
                    left: 196,
                    width: 43,
                    height: 43,
                    tips: 'R和r键',
                },
                {
                    keyName: 'T',
                    name: 'T',
                    keyID: 10020,
                    KeyCode: '20 00 17',
                    top: 88,
                    left: 240,
                    width: 43,
                    height: 43,
                    tips: 'T和t键',
                },
                {
                    keyName: 'Y',
                    name: 'Y',
                    keyID: 10025,
                    KeyCode: '20 00 1C',
                    top: 88,
                    left: 284,
                    width: 43,
                    height: 43,
                    tips: 'Y和y键',
                },
                {
                    keyName: 'U',
                    name: 'U',
                    keyID: 10021,
                    KeyCode: '20 00 18',
                    top: 88,
                    left: 328,
                    width: 43,
                    height: 43,
                    tips: 'U和u键',
                },
                {
                    keyName: 'I',
                    name: 'I',
                    keyID: 10009,
                    KeyCode: '20 00 0C',
                    top: 88,
                    left: 372,
                    width: 43,
                    height: 43,
                    tips: 'I和i键',
                },
                {
                    keyName: 'O',
                    name: 'O',
                    keyID: 10015,
                    KeyCode: '20 00 12',
                    top: 88,
                    left: 416,
                    width: 43,
                    height: 43,
                    tips: 'O和o键',
                },
                {
                    keyName: 'P',
                    name: 'P',
                    keyID: 10016,
                    KeyCode: '20 00 13',
                    top: 88,
                    left: 460,
                    width: 43,
                    height: 43,
                    tips: 'P和p键',
                },
                {
                    keyName: '[{',
                    name: '[{',
                    keyID: 10067,
                    KeyCode: '20 00 2F',
                    top: 88,
                    left: 504,
                    width: 43,
                    height: 43,
                    tips: '单击为[按住SHIFT单击为{',
                },
                {
                    keyName: ']}',
                    name: ']}',
                    keyID: 10068,
                    KeyCode: '20 00 30',
                    top: 88,
                    left: 548,
                    width: 43,
                    height: 43,
                    tips: '单击为]按住SHIFT单击为}',
                },
                {
                    keyName: '\\|',
                    name: '\\|',
                    keyID: 10069,
                    KeyCode: '20 00 31',
                    top: 88,
                    left: 592,
                    width: 60,
                    height: 43,
                    tips: '单击为\\按住SHIFT单击为|',
                },
                {
                    keyName: 'DEL',
                    name: 'DEL',
                    keyID: 10059,
                    KeyCode: '20 00 4C',
                    top: 88,
                    left: 676,
                    width: 43,
                    height: 43,
                    tips: '删除键(全称:Delete)',
                },
                {
                    keyName: 'END',
                    name: 'END',
                    keyID: 10058,
                    KeyCode: '20 00 4D',
                    top: 88,
                    left: 720,
                    width: 43,
                    height: 43,
                    tips: '回到窗口的最终位置或回到本行的最末端',
                },
                {
                    keyName: 'PGDN',
                    name: 'PGDN',
                    keyID: 10057,
                    KeyCode: '20 00 4E',
                    top: 88,
                    left: 764,
                    width: 43,
                    height: 43,
                    tips: '将页面向下滑动(全称:Page Down)',
                },
                {
                    keyName: '7',
                    name: '7',
                    keyID: 10101,
                    KeyCode: '20 00 5F',
                    top: 88,
                    left: 828,
                    width: 43,
                    height: 43,
                    tips: 'Num Lock打开时为7，关闭时为HOME键',
                },
                {
                    keyName: '8',
                    name: '8',
                    keyID: 10102,
                    KeyCode: '20 00 60',
                    top: 88,
                    left: 872,
                    width: 43,
                    height: 43,
                    tips: 'Num Lock打开时为8,关闭时为上键',
                },
                {
                    keyName: '9',
                    name: '9',
                    keyID: 10103,
                    KeyCode: '20 00 61',
                    top: 88,
                    left: 916,
                    width: 43,
                    height: 43,
                    tips: 'Num Lock打开时为9,关闭时为PGUP键,',
                },
                {
                    keyName: '+',
                    name: '+',
                    keyID: 10092,
                    KeyCode: '20 00 57',
                    top: 88,
                    left: 960,
                    width: 43,
                    height: 84,
                    tips: '+',
                },
                {
                    keyName: 'Caps',
                    name: 'Caps',
                    keyID: 10029,
                    KeyCode: '20 00 39',
                    top: 132,
                    left: 0,
                    width: 70,
                    height: 43,
                    tips: '切换字母输入为大写或小写模式(全称:CapsLock)',
                },
                {
                    keyName: 'A',
                    name: 'A',
                    keyID: 10001,
                    KeyCode: '20 00 04',
                    top: 132,
                    left: 74,
                    width: 43,
                    height: 43,
                    tips: 'A和a键',
                },
                {
                    keyName: 'S',
                    name: 'S',
                    keyID: 1019,
                    KeyCode: '20 00 16',
                    top: 132,
                    left: 118,
                    width: 43,
                    height: 43,
                    tips: 'S和s键',
                },
                {
                    keyName: 'D',
                    name: 'D',
                    keyID: 10004,
                    KeyCode: '20 00 07',
                    top: 132,
                    left: 162,
                    width: 43,
                    height: 43,
                    tips: 'D和d键',
                },

                {
                    keyName: 'F',
                    name: 'F',
                    keyID: 10006,
                    KeyCode: '20 00 09',
                    top: 132,
                    left: 206,
                    width: 43,
                    height: 43,
                    tips: 'F和f键',
                },
                {
                    keyName: 'G',
                    name: 'G',
                    keyID: 10007,
                    KeyCode: '20 00 0A',
                    top: 132,
                    left: 250,
                    width: 43,
                    height: 43,
                    tips: 'G和g键',
                },
                {
                    keyName: 'H',
                    name: 'H',
                    keyID: 10008,
                    KeyCode: '20 00 0B',
                    top: 132,
                    left: 294,
                    width: 43,
                    height: 43,
                    tips: 'H和h键',
                },
                {
                    keyName: 'J',
                    name: 'J',
                    keyID: 10010,
                    KeyCode: '20 00 0D',
                    top: 132,
                    left: 338,
                    width: 43,
                    height: 43,
                    tips: 'J和j键',
                },
                {
                    keyName: 'K',
                    name: 'K',
                    keyID: 10011,
                    KeyCode: '20 00 0E',
                    top: 132,
                    left: 382,
                    width: 43,
                    height: 43,
                    tips: 'K和k键',
                },
                {
                    keyName: 'L',
                    name: 'L',
                    keyID: 10012,
                    KeyCode: '20 00 0F',
                    top: 132,
                    left: 426,
                    width: 43,
                    height: 43,
                    tips: 'L和l键',
                },
                {
                    keyName: ';:',
                    name: ';:',
                    keyID: 10070,
                    KeyCode: '20 00 33',
                    top: 132,
                    left: 470,
                    width: 43,
                    height: 43,
                    tips: '单击为;按住SHIFT单击为:',
                },
                {
                    keyName: '\'"',
                    name: '\'"',
                    keyID: 10071,
                    KeyCode: '20 00 34',
                    top: 132,
                    left: 514,
                    width: 43,
                    height: 43,
                    tips: '单击为\'按住SHIFT单击为”',
                },
                {
                    keyName: 'Enter',
                    name: 'Enter',
                    keyID: 10033,
                    KeyCode: '20 00 28',
                    top: 132,
                    left: 558,
                    width: 94,
                    height: 43,
                    tips: '常用于确认、提交、执行命令',
                },
                {
                    keyName: '4',
                    name: '4',
                    keyID: 10098,
                    KeyCode: '20 00 5C',
                    top: 132,
                    left: 828,
                    width: 43,
                    height: 43,
                    tips: 'Num Lock打开时为4,关闭时为左键',
                },
                {
                    keyName: '5',
                    name: '5',
                    keyID: 10099,
                    KeyCode: '20 00 5D',
                    top: 132,
                    left: 872,
                    width: 43,
                    height: 43,
                    tips: 'Num Lock打开时为5，关闭时无作用',
                },
                {
                    keyName: '6',
                    name: '6',
                    keyID: 10100,
                    KeyCode: '20 00 5E',
                    top: 132,
                    left: 916,
                    width: 43,
                    height: 43,
                    tips: 'Num Lock打开时为6，关闭时为右键',
                },
                {
                    keyName: 'Shift',
                    name: 'Shift',
                    keyID: 10034,
                    KeyCode: '20 02 00',
                    top: 176,
                    left: 0,
                    width: 94,
                    height: 43,
                    tips: '左Shift键(全称:Left Shift)',
                },
                {
                    keyName: 'Z',
                    name: 'Z',
                    keyID: 10026,
                    KeyCode: '20 00 1D',
                    top: 176,
                    left: 98,
                    width: 43,
                    height: 43,
                    tips: 'Z和z键',
                },
                {
                    keyName: 'X',
                    name: 'X',
                    keyID: 10024,
                    KeyCode: '20 00 1B',
                    top: 176,
                    left: 142,
                    width: 43,
                    height: 43,
                    tips: 'X和x键',
                },
                {
                    keyName: 'C',
                    name: 'C',
                    keyID: 10003,
                    KeyCode: '20 00 06',
                    top: 176,
                    left: 186,
                    width: 43,
                    height: 43,
                    tips: 'C和c键',
                },
                {
                    keyName: 'V',
                    name: 'V',
                    keyID: 10022,
                    KeyCode: '20 00 19',
                    top: 176,
                    left: 230,
                    width: 43,
                    height: 43,
                    tips: 'V和v键',
                },


                {
                    keyName: 'B',
                    name: 'B',
                    keyID: 10002,
                    KeyCode: '20 00 05',
                    top: 176,
                    left: 274,
                    width: 43,
                    height: 43,
                    tips: 'B和b键',
                },
                {
                    keyName: 'N',
                    name: 'N',
                    keyID: 10014,
                    KeyCode: '20 00 11',
                    top: 176,
                    left: 318,
                    width: 43,
                    height: 43,
                    tips: 'N和n键',
                },
                {
                    keyName: 'M',
                    name: 'M',
                    keyID: 10013,
                    KeyCode: '20 00 10',
                    top: 176,
                    left: 362,
                    width: 43,
                    height: 43,
                    tips: 'M和m键',
                },
                {
                    keyName: ',<',
                    name: ',<',
                    keyID: 10072,
                    KeyCode: '20 00 36',
                    top: 176,
                    left: 406,
                    width: 43,
                    height: 43,
                    tips: '单击为，按住SHIFT单击为<',
                },
                {
                    keyName: '.>',
                    name: '.>',
                    keyID: 10073,
                    KeyCode: '20 00 37',
                    top: 176,
                    left: 450,
                    width: 43,
                    height: 43,
                    tips: '单击为.按住SHIFT单击为>',
                },
                {
                    keyName: '/?',
                    name: '/?',
                    keyID: 10074,
                    KeyCode: '20 00 38',
                    top: 176,
                    left: 494,
                    width: 43,
                    height: 43,
                    tips: '单击为/按住SHIFT单击为?',
                },

                {
                    keyName: 'Shift',
                    name: 'Shift',
                    keyID: 10035,
                    KeyCode: '20 20 00',
                    top: 176,
                    left: 538,
                    width: 114,
                    height: 43,
                    tips: '右Shift键(全称:Right Shift)',
                },

                {
                    keyName: '↑',
                    name: '↑',
                    keyID: 10060,
                    KeyCode: '20 00 52',
                    top: 176,
                    left: 720,
                    width: 43,
                    height: 43,
                    tips: '方向上键',
                },
                {
                    keyName: '1',
                    name: '1',
                    keyID: 10095,
                    KeyCode: '20 00 59',
                    top: 176,
                    left: 828,
                    width: 43,
                    height: 43,
                    tips: 'Num Lock打开时为1,关闭时为End键',
                },
                {
                    keyName: '2',
                    name: '2',
                    keyID: 10096,
                    KeyCode: '20 00 5A',
                    top: 176,
                    left: 872,
                    width: 43,
                    height: 43,
                    tips: 'Num Lock打开时为2，关闭时为下键',
                },
                {
                    keyName: '3',
                    name: '3',
                    keyID: 10097,
                    KeyCode: '20 00 5B',
                    top: 176,
                    left: 916,
                    width: 43,
                    height: 43,
                    tips: 'Num Lock打开时为3,关闭时为PGDN键',
                },
                {
                    keyName: 'Enter',
                    name: 'Enter',
                    keyID: 10093,
                    KeyCode: '20 00 58',
                    top: 176,
                    left: 960,
                    width: 43,
                    height: 84,
                    tips: '数字键盘上的Enter键(全称:Numpad Enter)',
                },
                {
                    keyName: 'Ctrl',
                    name: 'Ctrl',
                    keyID: 10036,
                    KeyCode: '20 01 00',
                    top: 220,
                    left: 0,
                    width: 50,
                    height: 43,
                    tips: '左Ctrl键(全称:Left Ctrl)',
                },
                {
                    keyName: 'Win',
                    name: 'Win',
                    keyID: 10040,
                    KeyCode: '20 08 00',
                    top: 220,
                    left: 54,
                    width: 50,
                    height: 43,
                    tips: 'Left windows/Left Command',
                },
                {
                    keyName: 'Alt',
                    name: 'Alt',
                    keyID: 10038,
                    KeyCode: '20 04 00',
                    top: 220,
                    left: 108,
                    width: 50,
                    height: 43,
                    tips: 'Left Alt/Left Option',
                },
                {
                    keyName: 'Space',
                    name: 'Space',
                    keyID: 10031,
                    KeyCode: '20 00 2C',
                    top: 220,
                    left: 162,
                    width: 274,
                    height: 43,
                    tips: '空格键(全称:Space Bar)',
                },

                {
                    keyName: 'Alt',
                    name: 'Alt',
                    keyID: 10039,
                    KeyCode: '20 40 00',
                    top: 220,
                    left: 440,
                    width: 50,
                    height: 43,
                    tips: 'Right Alt/Right Option',
                },

                {
                    keyName: 'Win',
                    name: 'Win',
                    keyID: 10041,
                    KeyCode: '20 80 00',
                    top: 220,
                    left: 494,
                    width: 50,
                    height: 43,
                    tips: 'Right windows/Right Command',
                },
                {
                    keyName: 'Menu',
                    name: 'Menu',
                    keyID: 10032,
                    KeyCode: '20 00 65',
                    top: 220,
                    left: 548,
                    width: 50,
                    height: 43,
                    tips: '打开程序或系统中的菜单选项',
                },
                {
                    keyName: 'Ctrl',
                    name: 'Ctrl',
                    keyID: 10037,
                    KeyCode: '20 10 00',
                    top: 220,
                    left: 602,
                    width: 50,
                    height: 43,
                    tips: '右Ctrl键(全称:Right Ctrl)',
                },
                {
                    keyName: '←',
                    name: '←',
                    keyID: 10062,
                    KeyCode: '20 00 50',
                    top: 220,
                    left: 676,
                    width: 43,
                    height: 43,
                    tips: '方向左键',
                },
                {
                    keyName: '↓',
                    name: '↓',
                    keyID: 10061,
                    KeyCode: '20 00 51',
                    top: 220,
                    left: 720,
                    width: 43,
                    height: 43,
                    tips: '方向下键',
                },

                {
                    keyName: '→',
                    name: '→',
                    keyID: 10063,
                    KeyCode: '20 00 4F',
                    top: 220,
                    left: 764,
                    width: 43,
                    height: 43,
                    tips: '方向右键',
                },
                {
                    keyName: '0',
                    name: '0',
                    keyID: 10104,
                    KeyCode: '20 00 62',
                    top: 220,
                    left: 828,
                    width: 84,
                    height: 43,
                    tips: 'Num Lock打开时为0,关闭时为INS键',
                },
                {
                    keyName: '.',
                    name: '.',
                    keyID: 10094,
                    KeyCode: '20 00 63',
                    top: 220,
                    left: 916,
                    width: 43,
                    height: 43,
                    tips: 'Num Lock打开时为.,关闭时为DEL键',
                },
                // {
                //     keyName: 'Fn',
                //     name: 'Fn',
                // keyID: 10000,
                //     KeyCode: 'A0 01 00',
                //     top: 0,
                //     left: 0,
                //     width: 43,
                //     height: 43,
                // tips: '跳转到托盘',
                // },
                // {
                //     keyName: 'Fn2',
                //     name: 'Fn2',
                // keyID: 10105,
                //KeyCode: 'A0 D1 00',
                //     top: 0,
                //     left: 0,
                //     width: 43,
                //     height: 43,
                // tips: '跳转到托盘',
                // },
            ]
        },
        {
            title: "鼠标功能",
            keys: [
                {
                    keyName: '鼠标左键',
                    name: '鼠标左键',
                    keyID: 20000,
                    KeyCode: '10 01 00',
                    icon: mouseLeft,
                    tips: '鼠标左键',
                },
                {
                    keyName: '鼠标右键',
                    name: '鼠标右键',
                    keyID: 20001,
                    KeyCode: '10 02 00',
                    icon: mouseRight,
                    tips: '鼠标右键',
                },
                {
                    keyName: '鼠标中键',
                    name: '鼠标中键',
                    keyID: 20002,
                    KeyCode: '10 04 00',
                    icon: mouseMiddle,
                    tips: '鼠标中键',
                },
                {
                    keyName: '鼠标前进',
                    name: '鼠标前进',
                    keyID: 20003,
                    KeyCode: '10 10 00',
                    icon: mouseForward,
                    tips: '鼠标前进',
                },
                {
                    keyName: '鼠标后退',
                    name: '鼠标后退',
                    keyID: 20004,
                    KeyCode: '10 08 00',
                    icon: mouseBackward,
                    tips: '鼠标后退',
                },
                {
                    keyName: '滚轮上',
                    name: '滚轮上',
                    keyID: 20008,
                    KeyCode: '12 00 FF',
                    icon: mouseWheelUp,
                    tips: '滚轮上',
                },
                {
                    keyName: '滚轮下',
                    name: '滚轮下',
                    keyID: 20009,
                    KeyCode: '12 00 01',
                    icon: mouseWheelDown,
                    tips: '滚轮下',
                },
                {
                    keyName: 'DPI+',
                    name: 'DPI+',
                    keyID: 20005,
                    KeyCode: '10 08 00',
                    icon: mouseBackward,
                    tips: 'DPI+',
                },
                {
                    keyName: 'DPI-',
                    name: 'DPI-',
                    keyID: 20006,
                    KeyCode: '12 00 FF',
                    icon: mouseWheelUp,
                    tips: 'DPI-',
                },
                {
                    keyName: 'DPI循环',
                    name: 'DPI循环',
                    keyID: 20007,
                    KeyCode: '12 00 01',
                    icon: mouseWheelDown,
                    tips: 'DPI循环',
                },
            ]
        },
        {
            title: "特殊字符",
            keys: [
                {
                    keyName: '缩小',
                    name: '缩小',
                    keyID: 30000,
                    KeyCode: '20 01 2D',
                    icon: reduce,
                    tips: '缩小',
                },
                {
                    keyName: '放大',
                    name: '放大',
                    keyID: 30001,
                    KeyCode: '20 01 2E',
                    icon: zoomIn,
                    tips: '放大',
                },
                {
                    keyName: '复位',
                    name: '复位',
                    keyID: 30002,
                    KeyCode: '20 01 27',
                    icon: reset,
                    tips: '复位',
                },
                {
                    keyName: '恢复',
                    name: '恢复',
                    keyID: 30003,
                    KeyCode: '20 01 1C',
                    icon: recovery,
                    tips: '恢复',
                },
                {
                    keyName: '撤销',
                    name: '撤销',
                    keyID: 30004,
                    KeyCode: '20 01 1D',
                    icon: undo,
                    tips: '撤销',
                },
                {
                    keyName: '全选',
                    name: '全选',
                    keyID: 30005,
                    KeyCode: '20 01 04',
                    icon: selectAll,
                    tips: '全选',
                },
                {
                    keyName: '新建',
                    name: '新建',
                    keyID: 30006,
                    KeyCode: '20 01 11',
                    icon: create,
                    tips: '新建',
                },
                {
                    keyName: '复制',
                    name: '复制',
                    keyID: 30007,
                    KeyCode: '20 01 06',
                    icon: copy,
                    tips: '复制',
                },
                {
                    keyName: '剪切',
                    name: '剪切',
                    keyID: 30008,
                    KeyCode: '20 01 1B',
                    icon: cut,
                    tips: '剪切',
                },
                {
                    keyName: '粘贴',
                    name: '粘贴',
                    keyID: 30009,
                    KeyCode: '20 01 19',
                    icon: paste,
                    tips: '粘贴',
                },
                {
                    keyName: '保存',
                    name: '保存',
                    keyID: 30010,
                    KeyCode: '20 01 16',
                    icon: save,
                    tips: '保存',
                },
                {
                    keyName: '打开',
                    name: '打开',
                    keyID: 30011,
                    KeyCode: '20 01 12',
                    icon: open,
                    tips: '打开',
                },
                {
                    keyName: '新建项',
                    name: '新建项',
                    keyID: 30012,
                    KeyCode: '20 01 17',
                    icon: newItem,
                    tips: '新建项',
                },
                {
                    keyName: '关闭项',
                    name: '关闭项',
                    keyID: 30013,
                    KeyCode: '20 01 1A',
                    icon: closeItem,
                    tips: '关闭项',
                },
                {
                    keyName: '后退(键盘)',
                    name: '后退(键盘)',
                    keyID: 30014,
                    KeyCode: '20 04 50',
                    icon: back,
                    tips: '后退(键盘)',
                },
                {
                    keyName: '前进(键盘)',
                    name: '前进(键盘)',
                    keyID: 30015,
                    KeyCode: '20 04 4F',
                    icon: forward,
                    tips: '前进(键盘)',
                },
                {
                    keyName: '任务栏',
                    name: '任务栏',
                    keyID: 30016,
                    KeyCode: '20 08 2B',
                    icon: taskBar,
                    tips: '任务栏',
                },
                {
                    keyName: '打开叙述',
                    name: '打开叙述',
                    keyID: 30017,
                    KeyCode: '20 09 58',
                    icon: openDescription,
                    tips: '打开叙述',
                },
                {
                    keyName: '循环任务栏应用程序',
                    name: '循环任务栏应用程序',
                    keyID: 30018,
                    KeyCode: '20 08 17',
                    icon: loopTaskBarApp,
                    tips: '循环任务栏应用程序',
                },
                {
                    keyName: '行动中心',
                    name: '行动中心',
                    keyID: 30019,
                    KeyCode: '20 08 04',
                    icon: actionCenter,
                    tips: '行动中心',
                },
                {
                    keyName: '文件资源管理器',
                    name: '文件资源管理器',
                    keyID: 30020,
                    KeyCode: '20 08 08',
                    icon: fileExplorer,
                    tips: '文件资源管理器',
                },
                {
                    keyName: 'Windows设置中心',
                    name: 'Windows设置中心',
                    keyID: 30021,
                    KeyCode: '20 08 0C',
                    icon: windowsSettingsCenter,
                    tips: 'Windows设置中心',
                },
                {
                    keyName: '投屏到其他设备',
                    name: '投屏到其他设备',
                    keyID: 30022,
                    KeyCode: '20 08 0E',
                    icon: castToOtherDevice,
                    tips: '投屏到其他设备',
                },
                {
                    keyName: '跳转到托盘',
                    name: '跳转到托盘',
                    keyID: 30023,
                    KeyCode: '20 08 05',
                    icon: jumpToTray,
                    tips: '跳转到托盘',
                },
                {
                    keyName: '启动xbox游戏栏',
                    name: '启动xbox游戏栏',
                    keyID: 30024,
                    KeyCode: '20 08 0A',
                    icon: startXboxGameBar,
                    tips: '启动xbox游戏栏',
                },
                {
                    keyName: '运行',
                    name: '运行',
                    keyID: 30025,
                    KeyCode: '20 08 15',
                    icon: run,
                    tips: '运行',
                },
                {
                    keyName: '搜索',
                    name: '搜索',
                    keyID: 30026,
                    KeyCode: '20 08 16',
                    icon: search,
                    tips: '搜索',
                },
                {
                    keyName: '显示设置',
                    name: '显示设置',
                    keyID: 30027,
                    KeyCode: '20 08 18',
                    icon: displaySettings,
                    tips: '显示设置',
                },
                {
                    keyName: '简易菜单',
                    name: '简易菜单',
                    keyID: 30028,
                    KeyCode: '20 08 1B',
                    icon: simpleMenu,
                    tips: '简易菜单',
                },
                {
                    keyName: '表情框',
                    name: '表情框',
                    keyID: 30029,
                    KeyCode: '20 08 37',
                    icon: emojiBox,
                    tips: '表情框',
                },
                {
                    keyName: '开始菜单',
                    name: '开始菜单',
                    keyID: 30030,
                    KeyCode: '20 01 29',
                    icon: startMenu,
                    tips: '开始菜单',
                },
                {
                    keyName: '转换窗口',
                    name: '转换窗口',
                    keyID: 30031,
                    KeyCode: '20 04 2B',
                    icon: switchWindow,
                    tips: '转换窗口',
                },
                {
                    keyName: '结束应用',
                    name: '结束应用',
                    keyID: 30032,
                    KeyCode: '20 04 3D',
                    icon: endApp,
                    tips: '结束应用',
                },
                {
                    keyName: '切换到下一个应用',
                    name: '切换到下一个应用',
                    keyID: 30033,
                    KeyCode: '20 04 29',
                    icon: switchToNextApp,
                    tips: '切换到下一个应用',
                },

                {
                    keyName: '播放/暂停',
                    name: '播放/暂停',
                    keyID: 30034,
                    KeyCode: '30 CD 00',
                    icon: playPause,
                    tips: '播放/暂停',
                },
                {
                    keyName: '静音',
                    name: '静音',
                    keyID: 30035,
                    KeyCode: '30 E2 00',
                    icon: mute,
                    tips: '静音',
                },
                {
                    keyName: '停止播放',
                    name: '停止播放',
                    keyID: 30036,
                    KeyCode: '30 B7 00',
                    icon: stopPlay,
                    tips: '停止播放',
                },
                {
                    keyName: '上一曲',
                    name: '上一曲',
                    keyID: 30037,
                    KeyCode: '30 B6 00',
                    icon: previousTrack,
                    tips: '上一曲',
                },
                {
                    keyName: '下一曲',
                    name: '下一曲',
                    keyID: 30038,
                    KeyCode: '30 B5 00',
                    icon: nextTrack,
                    tips: '下一曲',
                },
                {
                    keyName: '音量+',
                    name: '音量+',
                    keyID: 30039,
                    KeyCode: '30 E9 00',
                    icon: volumeUp,
                    tips: '音量+',
                },
                {
                    keyName: '音量-',
                    name: '音量-',
                    keyID: 30040,
                    KeyCode: '30 EA 00',
                    icon: volumeDown,
                    tips: '音量-',
                },
                {
                    keyName: '浏览器主页',
                    name: '浏览器主页',
                    keyID: 30041,
                    KeyCode: '30 23 02',
                    icon: browserHomeIcon,
                    tips: '浏览器主页',
                },
                {
                    keyName: '计算器',
                    name: '计算器',
                    keyID: 30042,
                    KeyCode: '30 92 01',
                    icon: calculator,
                    tips: '计算器',
                },
                {
                    keyName: '邮件',
                    name: '邮件',
                    keyID: 30043,
                    KeyCode: '30 8A 01',
                    icon: email,
                    tips: '邮件',
                },
                {
                    keyName: '我的电脑',
                    name: '我的电脑',
                    keyID: 30044,
                    KeyCode: '30 94 01',
                    icon: computer,
                    tips: '我的电脑',
                },
                {
                    keyName: '收藏夹',
                    name: '收藏夹',
                    keyID: 30045,
                    KeyCode: '30 2A 02',
                    icon: bookmark,
                    tips: '收藏夹',
                },
                {
                    keyName: '关闭窗口',
                    name: '关闭窗口',
                    keyID: 30046,
                    KeyCode: '20 40 3D',
                    icon: closeWindow,
                    tips: '关闭窗口',
                },
                {
                    keyName: '锁定计算机',
                    name: '锁定计算机',
                    keyID: 30047,
                    KeyCode: '20 08 0F',
                    icon: lockComputer,
                    tips: '锁定计算机',
                },
                {
                    keyName: '显示桌面',
                    name: '显示桌面',
                    keyID: 30048,
                    KeyCode: '20 08 07',
                    icon: showDesktop,
                    tips: '显示桌面',
                },
                {
                    keyName: 'Windows安全屏幕',
                    name: 'Windows安全屏幕',
                    keyID: 30049,
                    KeyCode: '20 05 4C',
                    icon: windowsSecurityScreen,
                    tips: 'Windows安全屏幕',
                },
                {
                    keyName: '任务管理器',
                    name: '任务管理器',
                    keyID: 30050,
                    KeyCode: '20 03 29',
                    icon: taskManager,
                    tips: '任务管理器',
                },
                {
                    keyName: '屏幕亮度+',
                    name: '屏幕亮度+',
                    keyID: 30051,
                    KeyCode: '30 6F 00',
                    icon: screenBrightnessUp,
                    tips: '屏幕亮度+',
                },
                {
                    keyName: '屏幕亮度-',
                    name: '屏幕亮度-',
                    keyID: 30052,
                    KeyCode: '30 70 00',
                    icon: screenBrightnessDown,
                    tips: '屏幕亮度-',
                },
            ]
        }
    ]
}
